name: Deps

on: push

jobs:

  deps:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Validate dependencies
        run: yarn install --immutable --immutable-cache --check-cache
